### ISSUE TITLE
我再项目下使用出错

### ISSUE THREAD

**Issue by LuoHao-study** [TJ-XiaJiaHao/wx-minifier#1]
我再项目下使用却出现ENOENT: no such file or directory, mkdir错误，文件和目录都是有的，这个怎么解决啊？

**Comment by TJ-XiaJiaHao** [comment]
> 我再项目下使用却出现ENOENT: no such file or directory, mkdir错误，文件和目录都是有的，这个怎么解决啊？

**Comment by TJ-XiaJiaHao** [comment]
@15362532197 可以传一下报错截图嘛？

**Comment by LuoHao-study** [comment]
> @ 15362532197可以传一下报错截图嘛？

![QQ截图20190411163620](https://user-images.githubusercontent.com/29995788/55942915-120a3300-5c78-11e9-9021-809f62ae0ef0.png)
